### ISSUE TITLE
Unable to pub get - flutter_test from sdk depends on meta 1.3.0-nullsafety.3 and redux_toolkit >=0.1.3 

### ISSUE THREAD

**Issue by viralpatel** [mrnkr/redux_toolkit#1]
Hello, I am trying to use redux_toolkit package with latest flutter version.

```
$ flutter --version
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (13 days ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0

```

After adding redux_toolkit dependency and I try flutter pub get, I am getting following error.

```
Because every version of flutter_test from sdk depends on meta 1.3.0-nullsafety.3 and redux_toolkit >=0.1.3 depends on meta >=1.1.8 <=1.2.3, flutter_test from sdk is incompatible with redux_toolkit >=0.1.3.
So, because sampleapp depends on both redux_toolkit ^0.1.3 and flutter_test any from sdk, version solving failed.
```

Do you see anything wrong or its just the 0.1.3 version is not compatible with latest flutter?

**Comment by mrnkr** [comment]
Hi @viralpatel 

First of all I'd like to apologize for not getting back to you any sooner... I just noticed this issue today.

I've just uploaded version `0.1.4` of the package to pub.dev and you'll notice it now supports all versions through to the next major release of each package, most importantly, `meta` which was the one giving you issues.

I tested this locally with the latest version of flutter to date (stable - 1.22.5) and could reproduce the error with version `0.1.3` and didn't have it with version `0.1.4`.

I'll leave this issue open for now in case you want to let me know about any related issues you may find.

Again, sorry for the late response.
